In [1]:
import requests
import pandas as pd

url = "http://96.9.212.102:8000/orders"

response = requests.get(url)

data = response.json()

df = pd.DataFrame(data)

df.head()

/Users/ibrahimferel/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

   total_orders                                             orders
0           100  {'order_id': 10112, 'user_id': 29424, 'order_n...
1           100  {'order_id': 17133, 'user_id': 171465, 'order_...
2           100  {'order_id': 54348, 'user_id': 180536, 'order_...
3           100  {'order_id': 59229, 'user_id': 187506, 'order_...
4           100  {'order_id': 78774, 'user_id': 68568, 'order_n...

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   total_orders  100 non-null    int64
 1   orders        100 non-null    object
dtypes: int64(1), object(1)
memory usage: 1.7+ KB

In [3]:
df.head()

   total_orders                                             orders
0           100  {'order_id': 10112, 'user_id': 29424, 'order_n...
1           100  {'order_id': 17133, 'user_id': 171465, 'order_...
2           100  {'order_id': 54348, 'user_id': 180536, 'order_...
3           100  {'order_id': 59229, 'user_id': 187506, 'order_...
4           100  {'order_id': 78774, 'user_id': 68568, 'order_n...

In [4]:
df.sample(5)

    total_orders                                             orders
54           100  {'order_id': 1869640, 'user_id': 122615, 'orde...
22           100  {'order_id': 857614, 'user_id': 130461, 'order...
25           100  {'order_id': 883961, 'user_id': 96750, 'order_...
96           100  {'order_id': 3384498, 'user_id': 122900, 'orde...
30           100  {'order_id': 1002901, 'user_id': 167266, 'orde...

In [5]:
df.describe()

       total_orders
count         100.0
mean          100.0
std             0.0
min           100.0
25%           100.0
50%           100.0
75%           100.0
max           100.0

In [ ]:
df_parquet = pd.read_parquet("data_lake/task2/orders_20260517_234921.parquet")
df_parquet.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,product_name,department,aisle,add_to_cart_order,reordered
0,3899,76041,13,4,11,7.0,34067,Organic Honey,pantry,honeys syrups nectars,1,1
1,3899,76041,13,4,11,7.0,9550,Ancient Grain Original Granola,breakfast,granola,2,1
2,3899,76041,13,4,11,7.0,6962,Organic Whole Milk Plain Kefir,dairy eggs,milk,3,1
3,40469,113588,5,5,11,2.0,26940,Organic Large Green Asparagus,produce,fresh vegetables,1,1
4,40469,113588,5,5,11,2.0,24964,Organic Garlic,produce,fresh vegetables,2,1