In [1]:
import requests
import pandas as pd

url = "http://96.9.212.102:8000/orders"

response = requests.get(url)

data = response.json()

df = pd.DataFrame(data)

df.head()

   total_orders                                             orders
0           100  {'order_id': 84719, 'user_id': 173397, 'order_...
1           100  {'order_id': 130475, 'user_id': 55936, 'order_...
2           100  {'order_id': 223408, 'user_id': 114804, 'order...
3           100  {'order_id': 231942, 'user_id': 76290, 'order_...
4           100  {'order_id': 233700, 'user_id': 60908, 'order_...

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   total_orders  100 non-null    int64
 1   orders        100 non-null    object
dtypes: int64(1), object(1)
memory usage: 1.7+ KB

In [3]:
df.head()

   total_orders                                             orders
0           100  {'order_id': 84719, 'user_id': 173397, 'order_...
1           100  {'order_id': 130475, 'user_id': 55936, 'order_...
2           100  {'order_id': 223408, 'user_id': 114804, 'order...
3           100  {'order_id': 231942, 'user_id': 76290, 'order_...
4           100  {'order_id': 233700, 'user_id': 60908, 'order_...

In [4]:
df.sample(5)

    total_orders                                             orders
57           100  {'order_id': 2016597, 'user_id': 177673, 'orde...
59           100  {'order_id': 2047138, 'user_id': 148085, 'orde...
58           100  {'order_id': 2033668, 'user_id': 160226, 'orde...
38           100  {'order_id': 1452593, 'user_id': 102291, 'orde...
32           100  {'order_id': 1329431, 'user_id': 59631, 'order...

In [5]:
df.describe()

       total_orders
count         100.0
mean          100.0
std             0.0
min           100.0
25%           100.0
50%           100.0
75%           100.0
max           100.0